# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YELLOW APP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MCA
  pod 'Kingfisher'
  #pod 'WMSegmentControl'
  pod 'AARatingBar'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'GooglePlacePicker'
  pod 'NVActivityIndicatorView'
  pod 'XLPagerTabStrip'
  pod 'BSImagePicker' 

  target 'YELLOW APP Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YELLOW APP UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
